version: '3.3'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./www/:/var/www/html/
        ports:
            - 8002:80
    db:
        container_name: db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: developers
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
           - '8000:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
           - db
volumes:
   www:
