AWSTemplateFormatVersion: "2010-09-09"
  Description: "Resources for Instances and Buckets"
  Parameters: 
      WebPara: #LogicalID
        Type: String
        Default: t2.micro
        AllowedValues:
          - t2.small
          - t2.micro
          - t2.medium
          - t2.xlarge
        Description: Choose a instance
      NewPara: #Logical ID
        Type: String
        AllowedPattern: "[A-Za0-Z9]+"
      KeyPara: #Logical ID
        Type: String
        AllowedPattern: "[A-Za-Z]+"
      Bucket: #Logical ID
        Type: String
        AllowedPattern:
          Value: "[A-Za-z]+"
  Resources:
      WebInstance: #LogicalID
        Type: 'AWS::EC2::Instance'
        Properties:
          InstanceType: !Ref WebPara
          ImageId: ami-
          KeyName: !Ref NewPara
          Key: "Name"
          Value: !Ref KeyPara
      S3Bucket:
        Type: AWS::S3::BucketName
        Properties:
          BucketName: !Ref Bucket
  Outputs:
      InstanceId: 
        Value: !Ref WebInstance
      InstanceName:
        Value: !Ref WebInstance
