 AWSTemplateFormatVersion: "2010-09-09"
  Description: "my firth bucket in mumbai"
  Resources:
    S3Bucket: # logical id for unique
      Type: 'AWS::S3::Bucket' #cloudprovides/cloudservicename/data-values:
      Properties:
        BucketName: my-first-bucket-in-mumbai
      DeletionPolicy: Retain
  Outputs:
    BucketName:
        value: !Ref 'S3Bucket'       
