 AWSTemplateFormatVersion: "2010-09-09"
  Parameters:
    S3BucketName:
      Description: Enter Here Bucket Name
      type: string
    InstanceParammeter: # Logical Id
          Type: string
          Default: t2.micro
          AllowedValues:
            - t2.micro
            - t2.nano
            - t2.medium
            - t2.large
            - c2.large
            - m1.large
          Description: Choose t2.micro t2.nano t2.medium
  Resources:
    C2Instance: # Unique Logical Id
        Description: "This instance value refference to parammeters"
        Type: 'AWS::EC2::Instance'
        Properties:
          ImageId: ami-0cff7528ff583bf9a
          InstanceType: !Ref 'InstanceParammeter'
          KeyName: new2
          UserData:
            Fn::Base64:
              !Sub |
              #!/bin/bash
              apt-get update -y
              apt install docker -y
              service docker start
              apt install nginx -y
              service nginx start
    S3Bucket:
      Type: 'AWS::S3::Bucket' 
      Properties:
        BucketName: !Ref 'S3BucketName'
  Outputs:
    BucketName:
      Value: !Ref S3Bucket
