name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  lint-test-build-android-linux-web:
    name: Lint & Test & Build - Android, Linux, Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 12
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Test
        run: flutter test
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - name: Build for Linux
        run: flutter build linux
      - name: Build for Web
        run: flutter build web


