on: 
  push:
      branches:
        - master
name: Test, Build and Release apk
jobs:
  build:
    name: Build, test and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
    - run: flutter build appbundle --target-platform android-arm,android-arm64
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: |
           build/app/outputs/apk/release/*
           build/app/outputs/bundle/release/*
        retention-days: 5
